on:
  push:
    paths:
      - hello-world/*
  pull_request:
    paths:
      - hello-world/*
name: hello-world
jobs:
  hello-world:
    name: hello-world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js
        uses: actions/setup-node@master

      - name: On push
        if: github.event_name == 'push'
        run: echo 'Trigger on push'

      - name: On pull request
        if: github.event_name == 'pull_request'
        run: echo 'Trigger on PR'
